# Generated by Django 6.0.5 on 2026-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
